/*
목적:
- 기준일별 포트폴리오/위험요인 단위 한도 사용률을 산출한다.

테이블/컬럼 가정:
- RISK_EXPOSURE_DAILY: 일별 리스크 익스포저
- RISK_LIMIT_MASTER: 리스크 한도 마스터

주의:
- 실제 테이블명/컬럼명은 회사 개발망에서만 매핑한다.
*/

WITH EXPOSURE_BASE AS (
    SELECT
        E.BASE_DT,
        E.DESK_CD,
        E.PORTFOLIO_ID,
        E.RISK_FACTOR,
        SUM(E.EXPOSURE_AMT) AS EXPOSURE_AMT
    FROM RISK_EXPOSURE_DAILY E
    WHERE E.BASE_DT = :BASE_DT
    GROUP BY
        E.BASE_DT,
        E.DESK_CD,
        E.PORTFOLIO_ID,
        E.RISK_FACTOR
),
LIMIT_BASE AS (
    SELECT
        L.BASE_DT,
        L.PORTFOLIO_ID,
        L.RISK_FACTOR,
        L.LIMIT_AMT
    FROM RISK_LIMIT_MASTER L
    WHERE L.BASE_DT = :BASE_DT
      AND L.USE_YN = 'Y'
)
SELECT
    E.BASE_DT,
    E.DESK_CD,
    E.PORTFOLIO_ID,
    E.RISK_FACTOR,
    E.EXPOSURE_AMT,
    L.LIMIT_AMT,
    CASE
        WHEN L.LIMIT_AMT IS NULL OR L.LIMIT_AMT = 0 THEN NULL
        ELSE ROUND(ABS(E.EXPOSURE_AMT) / L.LIMIT_AMT * 100, 2)
    END AS LIMIT_USAGE_RATE,
    CASE
        WHEN L.LIMIT_AMT IS NULL THEN 'NO_LIMIT'
        WHEN ABS(E.EXPOSURE_AMT) > L.LIMIT_AMT THEN 'BREACH'
        WHEN ABS(E.EXPOSURE_AMT) / L.LIMIT_AMT >= 0.9 THEN 'WARNING'
        ELSE 'NORMAL'
    END AS LIMIT_STATUS
FROM EXPOSURE_BASE E
LEFT JOIN LIMIT_BASE L
  ON L.PORTFOLIO_ID = E.PORTFOLIO_ID
 AND L.RISK_FACTOR  = E.RISK_FACTOR
ORDER BY LIMIT_STATUS, LIMIT_USAGE_RATE DESC;
