/* 검증 1: 기준일 데이터 건수 */
SELECT BASE_DT, COUNT(*) AS ROW_CNT
FROM RISK_EXPOSURE_DAILY
WHERE BASE_DT = :BASE_DT
GROUP BY BASE_DT;

/* 검증 2: 한도 미매핑 */
SELECT E.PORTFOLIO_ID, E.RISK_FACTOR, COUNT(*) AS ROW_CNT
FROM RISK_EXPOSURE_DAILY E
LEFT JOIN RISK_LIMIT_MASTER L
  ON L.BASE_DT = E.BASE_DT
 AND L.PORTFOLIO_ID = E.PORTFOLIO_ID
 AND L.RISK_FACTOR = E.RISK_FACTOR
 AND L.USE_YN = 'Y'
WHERE E.BASE_DT = :BASE_DT
  AND L.PORTFOLIO_ID IS NULL
GROUP BY E.PORTFOLIO_ID, E.RISK_FACTOR
ORDER BY ROW_CNT DESC;

/* 검증 3: 원천 합계 대사 */
SELECT SUM(EXPOSURE_AMT) AS EXPOSURE_SUM
FROM RISK_EXPOSURE_DAILY
WHERE BASE_DT = :BASE_DT;
